// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// aggregate_cpp
List aggregate_cpp(List rasterbands, NumericVector dim, NumericVector res, NumericVector factor, int aggtype);
RcppExport SEXP velox_aggregate_cpp(SEXP rasterbandsSEXP, SEXP dimSEXP, SEXP resSEXP, SEXP factorSEXP, SEXP aggtypeSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type rasterbands(rasterbandsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dim(dimSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type res(resSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type factor(factorSEXP);
    Rcpp::traits::input_parameter< int >::type aggtype(aggtypeSEXP);
    __result = Rcpp::wrap(aggregate_cpp(rasterbands, dim, res, factor, aggtype));
    return __result;
END_RCPP
}
// getcoordinates_cpp
NumericMatrix getcoordinates_cpp(NumericVector dim, NumericVector res, NumericVector extent);
RcppExport SEXP velox_getcoordinates_cpp(SEXP dimSEXP, SEXP resSEXP, SEXP extentSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type dim(dimSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type res(resSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type extent(extentSEXP);
    __result = Rcpp::wrap(getcoordinates_cpp(dim, res, extent));
    return __result;
END_RCPP
}
// medianfocal_cpp
NumericMatrix medianfocal_cpp(NumericMatrix rasterband, int wrow, int wcol, int band);
RcppExport SEXP velox_medianfocal_cpp(SEXP rasterbandSEXP, SEXP wrowSEXP, SEXP wcolSEXP, SEXP bandSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type rasterband(rasterbandSEXP);
    Rcpp::traits::input_parameter< int >::type wrow(wrowSEXP);
    Rcpp::traits::input_parameter< int >::type wcol(wcolSEXP);
    Rcpp::traits::input_parameter< int >::type band(bandSEXP);
    __result = Rcpp::wrap(medianfocal_cpp(rasterband, wrow, wcol, band));
    return __result;
END_RCPP
}
// sumfocal_cpp
NumericMatrix sumfocal_cpp(NumericMatrix rasterband, NumericMatrix weights, int wrow, int wcol, int band);
RcppExport SEXP velox_sumfocal_cpp(SEXP rasterbandSEXP, SEXP weightsSEXP, SEXP wrowSEXP, SEXP wcolSEXP, SEXP bandSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type rasterband(rasterbandSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< int >::type wrow(wrowSEXP);
    Rcpp::traits::input_parameter< int >::type wcol(wcolSEXP);
    Rcpp::traits::input_parameter< int >::type band(bandSEXP);
    __result = Rcpp::wrap(sumfocal_cpp(rasterband, weights, wrow, wcol, band));
    return __result;
END_RCPP
}
// meanfocal_cpp
NumericMatrix meanfocal_cpp(NumericMatrix rasterband, NumericMatrix weights, int wrow, int wcol, int band);
RcppExport SEXP velox_meanfocal_cpp(SEXP rasterbandSEXP, SEXP weightsSEXP, SEXP wrowSEXP, SEXP wcolSEXP, SEXP bandSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type rasterband(rasterbandSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< int >::type wrow(wrowSEXP);
    Rcpp::traits::input_parameter< int >::type wcol(wcolSEXP);
    Rcpp::traits::input_parameter< int >::type band(bandSEXP);
    __result = Rcpp::wrap(meanfocal_cpp(rasterband, weights, wrow, wcol, band));
    return __result;
END_RCPP
}
// hittest_cpp
NumericMatrix hittest_cpp(List rasterbands, NumericVector dim, NumericVector extent, NumericVector res, NumericVector polyX, NumericVector polyY, int polyCorners);
RcppExport SEXP velox_hittest_cpp(SEXP rasterbandsSEXP, SEXP dimSEXP, SEXP extentSEXP, SEXP resSEXP, SEXP polyXSEXP, SEXP polyYSEXP, SEXP polyCornersSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type rasterbands(rasterbandsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dim(dimSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type extent(extentSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type res(resSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type polyX(polyXSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type polyY(polyYSEXP);
    Rcpp::traits::input_parameter< int >::type polyCorners(polyCornersSEXP);
    __result = Rcpp::wrap(hittest_cpp(rasterbands, dim, extent, res, polyX, polyY, polyCorners));
    return __result;
END_RCPP
}
// unhit_cpp
NumericMatrix unhit_cpp(NumericMatrix cmat, NumericVector polyX, NumericVector polyY, int polyCorners);
RcppExport SEXP velox_unhit_cpp(SEXP cmatSEXP, SEXP polyXSEXP, SEXP polyYSEXP, SEXP polyCornersSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type cmat(cmatSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type polyX(polyXSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type polyY(polyYSEXP);
    Rcpp::traits::input_parameter< int >::type polyCorners(polyCornersSEXP);
    __result = Rcpp::wrap(unhit_cpp(cmat, polyX, polyY, polyCorners));
    return __result;
END_RCPP
}
// im2col_cpp
NumericMatrix im2col_cpp(NumericMatrix rasterband, NumericVector dim, int wrow, int wcol, int band, double padval, int rowframe, int colframe, int rowstride, int colstride);
RcppExport SEXP velox_im2col_cpp(SEXP rasterbandSEXP, SEXP dimSEXP, SEXP wrowSEXP, SEXP wcolSEXP, SEXP bandSEXP, SEXP padvalSEXP, SEXP rowframeSEXP, SEXP colframeSEXP, SEXP rowstrideSEXP, SEXP colstrideSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type rasterband(rasterbandSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dim(dimSEXP);
    Rcpp::traits::input_parameter< int >::type wrow(wrowSEXP);
    Rcpp::traits::input_parameter< int >::type wcol(wcolSEXP);
    Rcpp::traits::input_parameter< int >::type band(bandSEXP);
    Rcpp::traits::input_parameter< double >::type padval(padvalSEXP);
    Rcpp::traits::input_parameter< int >::type rowframe(rowframeSEXP);
    Rcpp::traits::input_parameter< int >::type colframe(colframeSEXP);
    Rcpp::traits::input_parameter< int >::type rowstride(rowstrideSEXP);
    Rcpp::traits::input_parameter< int >::type colstride(colstrideSEXP);
    __result = Rcpp::wrap(im2col_cpp(rasterband, dim, wrow, wcol, band, padval, rowframe, colframe, rowstride, colstride));
    return __result;
END_RCPP
}
// col2im_cpp
NumericMatrix col2im_cpp(NumericMatrix rasterband, NumericVector dim, NumericMatrix colmat, int wrow, int wcol, int band, int rowframe, int colframe, int rowstride, int colstride);
RcppExport SEXP velox_col2im_cpp(SEXP rasterbandSEXP, SEXP dimSEXP, SEXP colmatSEXP, SEXP wrowSEXP, SEXP wcolSEXP, SEXP bandSEXP, SEXP rowframeSEXP, SEXP colframeSEXP, SEXP rowstrideSEXP, SEXP colstrideSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type rasterband(rasterbandSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dim(dimSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type colmat(colmatSEXP);
    Rcpp::traits::input_parameter< int >::type wrow(wrowSEXP);
    Rcpp::traits::input_parameter< int >::type wcol(wcolSEXP);
    Rcpp::traits::input_parameter< int >::type band(bandSEXP);
    Rcpp::traits::input_parameter< int >::type rowframe(rowframeSEXP);
    Rcpp::traits::input_parameter< int >::type colframe(colframeSEXP);
    Rcpp::traits::input_parameter< int >::type rowstride(rowstrideSEXP);
    Rcpp::traits::input_parameter< int >::type colstride(colstrideSEXP);
    __result = Rcpp::wrap(col2im_cpp(rasterband, dim, colmat, wrow, wcol, band, rowframe, colframe, rowstride, colstride));
    return __result;
END_RCPP
}
// color_cpp
NumericMatrix color_cpp(NumericMatrix rasterband, NumericMatrix coordvalmat, NumericVector extent, NumericVector res);
RcppExport SEXP velox_color_cpp(SEXP rasterbandSEXP, SEXP coordvalmatSEXP, SEXP extentSEXP, SEXP resSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type rasterband(rasterbandSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type coordvalmat(coordvalmatSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type extent(extentSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type res(resSEXP);
    __result = Rcpp::wrap(color_cpp(rasterband, coordvalmat, extent, res));
    return __result;
END_RCPP
}
// checktype_cpp
NumericVector checktype_cpp(List rasterbands);
RcppExport SEXP velox_checktype_cpp(SEXP rasterbandsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type rasterbands(rasterbandsSEXP);
    __result = Rcpp::wrap(checktype_cpp(rasterbands));
    return __result;
END_RCPP
}
