// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// aggregate_cpp
List aggregate_cpp(List rasterbands, NumericVector dim, NumericVector res, NumericVector factor, int aggtype);
RcppExport SEXP velox_aggregate_cpp(SEXP rasterbandsSEXP, SEXP dimSEXP, SEXP resSEXP, SEXP factorSEXP, SEXP aggtypeSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type rasterbands(rasterbandsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dim(dimSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type res(resSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type factor(factorSEXP);
    Rcpp::traits::input_parameter< int >::type aggtype(aggtypeSEXP);
    __result = Rcpp::wrap(aggregate_cpp(rasterbands, dim, res, factor, aggtype));
    return __result;
END_RCPP
}
// getcoordinates
NumericMatrix getcoordinates(NumericVector dim, NumericVector res, NumericVector extent);
RcppExport SEXP velox_getcoordinates(SEXP dimSEXP, SEXP resSEXP, SEXP extentSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type dim(dimSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type res(resSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type extent(extentSEXP);
    __result = Rcpp::wrap(getcoordinates(dim, res, extent));
    return __result;
END_RCPP
}
// medianfocal
NumericMatrix medianfocal(NumericMatrix rasterband, int wrow, int wcol, int band);
RcppExport SEXP velox_medianfocal(SEXP rasterbandSEXP, SEXP wrowSEXP, SEXP wcolSEXP, SEXP bandSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type rasterband(rasterbandSEXP);
    Rcpp::traits::input_parameter< int >::type wrow(wrowSEXP);
    Rcpp::traits::input_parameter< int >::type wcol(wcolSEXP);
    Rcpp::traits::input_parameter< int >::type band(bandSEXP);
    __result = Rcpp::wrap(medianfocal(rasterband, wrow, wcol, band));
    return __result;
END_RCPP
}
// sumfocal
NumericMatrix sumfocal(NumericMatrix rasterband, NumericMatrix weights, int wrow, int wcol, int band);
RcppExport SEXP velox_sumfocal(SEXP rasterbandSEXP, SEXP weightsSEXP, SEXP wrowSEXP, SEXP wcolSEXP, SEXP bandSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type rasterband(rasterbandSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< int >::type wrow(wrowSEXP);
    Rcpp::traits::input_parameter< int >::type wcol(wcolSEXP);
    Rcpp::traits::input_parameter< int >::type band(bandSEXP);
    __result = Rcpp::wrap(sumfocal(rasterband, weights, wrow, wcol, band));
    return __result;
END_RCPP
}
// meanfocal
NumericMatrix meanfocal(NumericMatrix rasterband, NumericMatrix weights, int wrow, int wcol, int band);
RcppExport SEXP velox_meanfocal(SEXP rasterbandSEXP, SEXP weightsSEXP, SEXP wrowSEXP, SEXP wcolSEXP, SEXP bandSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type rasterband(rasterbandSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< int >::type wrow(wrowSEXP);
    Rcpp::traits::input_parameter< int >::type wcol(wcolSEXP);
    Rcpp::traits::input_parameter< int >::type band(bandSEXP);
    __result = Rcpp::wrap(meanfocal(rasterband, weights, wrow, wcol, band));
    return __result;
END_RCPP
}
// hittest
NumericMatrix hittest(List rasterbands, NumericVector dim, NumericVector extent, NumericVector res, NumericVector polyX, NumericVector polyY, int polyCorners);
RcppExport SEXP velox_hittest(SEXP rasterbandsSEXP, SEXP dimSEXP, SEXP extentSEXP, SEXP resSEXP, SEXP polyXSEXP, SEXP polyYSEXP, SEXP polyCornersSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type rasterbands(rasterbandsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dim(dimSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type extent(extentSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type res(resSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type polyX(polyXSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type polyY(polyYSEXP);
    Rcpp::traits::input_parameter< int >::type polyCorners(polyCornersSEXP);
    __result = Rcpp::wrap(hittest(rasterbands, dim, extent, res, polyX, polyY, polyCorners));
    return __result;
END_RCPP
}
// unhit
NumericMatrix unhit(NumericMatrix cmat, NumericVector polyX, NumericVector polyY, int polyCorners);
RcppExport SEXP velox_unhit(SEXP cmatSEXP, SEXP polyXSEXP, SEXP polyYSEXP, SEXP polyCornersSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type cmat(cmatSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type polyX(polyXSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type polyY(polyYSEXP);
    Rcpp::traits::input_parameter< int >::type polyCorners(polyCornersSEXP);
    __result = Rcpp::wrap(unhit(cmat, polyX, polyY, polyCorners));
    return __result;
END_RCPP
}
// im2col_cpp
NumericMatrix im2col_cpp(NumericMatrix rasterband, NumericVector dim, int wrow, int wcol, int band, double padval, int rowframe, int colframe, int rowstride, int colstride);
RcppExport SEXP velox_im2col_cpp(SEXP rasterbandSEXP, SEXP dimSEXP, SEXP wrowSEXP, SEXP wcolSEXP, SEXP bandSEXP, SEXP padvalSEXP, SEXP rowframeSEXP, SEXP colframeSEXP, SEXP rowstrideSEXP, SEXP colstrideSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type rasterband(rasterbandSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dim(dimSEXP);
    Rcpp::traits::input_parameter< int >::type wrow(wrowSEXP);
    Rcpp::traits::input_parameter< int >::type wcol(wcolSEXP);
    Rcpp::traits::input_parameter< int >::type band(bandSEXP);
    Rcpp::traits::input_parameter< double >::type padval(padvalSEXP);
    Rcpp::traits::input_parameter< int >::type rowframe(rowframeSEXP);
    Rcpp::traits::input_parameter< int >::type colframe(colframeSEXP);
    Rcpp::traits::input_parameter< int >::type rowstride(rowstrideSEXP);
    Rcpp::traits::input_parameter< int >::type colstride(colstrideSEXP);
    __result = Rcpp::wrap(im2col_cpp(rasterband, dim, wrow, wcol, band, padval, rowframe, colframe, rowstride, colstride));
    return __result;
END_RCPP
}
// col2im_cpp
NumericMatrix col2im_cpp(NumericMatrix rasterband, NumericVector dim, NumericMatrix colmat, int wrow, int wcol, int band, int rowframe, int colframe, int rowstride, int colstride);
RcppExport SEXP velox_col2im_cpp(SEXP rasterbandSEXP, SEXP dimSEXP, SEXP colmatSEXP, SEXP wrowSEXP, SEXP wcolSEXP, SEXP bandSEXP, SEXP rowframeSEXP, SEXP colframeSEXP, SEXP rowstrideSEXP, SEXP colstrideSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type rasterband(rasterbandSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dim(dimSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type colmat(colmatSEXP);
    Rcpp::traits::input_parameter< int >::type wrow(wrowSEXP);
    Rcpp::traits::input_parameter< int >::type wcol(wcolSEXP);
    Rcpp::traits::input_parameter< int >::type band(bandSEXP);
    Rcpp::traits::input_parameter< int >::type rowframe(rowframeSEXP);
    Rcpp::traits::input_parameter< int >::type colframe(colframeSEXP);
    Rcpp::traits::input_parameter< int >::type rowstride(rowstrideSEXP);
    Rcpp::traits::input_parameter< int >::type colstride(colstrideSEXP);
    __result = Rcpp::wrap(col2im_cpp(rasterband, dim, colmat, wrow, wcol, band, rowframe, colframe, rowstride, colstride));
    return __result;
END_RCPP
}
// color
NumericMatrix color(NumericMatrix rasterband, NumericMatrix coordvalmat, NumericVector extent, NumericVector res);
RcppExport SEXP velox_color(SEXP rasterbandSEXP, SEXP coordvalmatSEXP, SEXP extentSEXP, SEXP resSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type rasterband(rasterbandSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type coordvalmat(coordvalmatSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type extent(extentSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type res(resSEXP);
    __result = Rcpp::wrap(color(rasterband, coordvalmat, extent, res));
    return __result;
END_RCPP
}
// readVelox
List readVelox(std::string path);
RcppExport SEXP velox_readVelox(SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    __result = Rcpp::wrap(readVelox(path));
    return __result;
END_RCPP
}
// writeVelox
void writeVelox(std::string path, List rasterbands, NumericVector dim, NumericVector extent, NumericVector res, std::string crs);
RcppExport SEXP velox_writeVelox(SEXP pathSEXP, SEXP rasterbandsSEXP, SEXP dimSEXP, SEXP extentSEXP, SEXP resSEXP, SEXP crsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    Rcpp::traits::input_parameter< List >::type rasterbands(rasterbandsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dim(dimSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type extent(extentSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type res(resSEXP);
    Rcpp::traits::input_parameter< std::string >::type crs(crsSEXP);
    writeVelox(path, rasterbands, dim, extent, res, crs);
    return R_NilValue;
END_RCPP
}
