# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

aggregate_cpp <- function(rasterbands, dim, res, factor, aggtype) {
    .Call('velox_aggregate_cpp', PACKAGE = 'velox', rasterbands, dim, res, factor, aggtype)
}

getcoordinates <- function(dim, res, extent) {
    .Call('velox_getcoordinates', PACKAGE = 'velox', dim, res, extent)
}

medianfocal <- function(rasterband, wrow, wcol, band) {
    .Call('velox_medianfocal', PACKAGE = 'velox', rasterband, wrow, wcol, band)
}

sumfocal <- function(rasterband, weights, wrow, wcol, band) {
    .Call('velox_sumfocal', PACKAGE = 'velox', rasterband, weights, wrow, wcol, band)
}

meanfocal <- function(rasterband, weights, wrow, wcol, band) {
    .Call('velox_meanfocal', PACKAGE = 'velox', rasterband, weights, wrow, wcol, band)
}

hittest <- function(rasterbands, dim, extent, res, polyX, polyY, polyCorners) {
    .Call('velox_hittest', PACKAGE = 'velox', rasterbands, dim, extent, res, polyX, polyY, polyCorners)
}

unhit <- function(cmat, polyX, polyY, polyCorners) {
    .Call('velox_unhit', PACKAGE = 'velox', cmat, polyX, polyY, polyCorners)
}

im2col_cpp <- function(rasterband, dim, wrow, wcol, band, padval, rowframe, colframe, rowstride, colstride) {
    .Call('velox_im2col_cpp', PACKAGE = 'velox', rasterband, dim, wrow, wcol, band, padval, rowframe, colframe, rowstride, colstride)
}

col2im_cpp <- function(rasterband, dim, colmat, wrow, wcol, band, rowframe, colframe, rowstride, colstride) {
    .Call('velox_col2im_cpp', PACKAGE = 'velox', rasterband, dim, colmat, wrow, wcol, band, rowframe, colframe, rowstride, colstride)
}

color <- function(rasterband, coordvalmat, extent, res) {
    .Call('velox_color', PACKAGE = 'velox', rasterband, coordvalmat, extent, res)
}

readVelox <- function(path) {
    .Call('velox_readVelox', PACKAGE = 'velox', path)
}

writeVelox <- function(path, rasterbands, dim, extent, res, crs) {
    invisible(.Call('velox_writeVelox', PACKAGE = 'velox', path, rasterbands, dim, extent, res, crs))
}

